# https://taskfile.dev

version: '3'

tasks:
  cs:
    cmds:
      - tools/bin/php-cs-fixer check
    silent: true

  cs.fix:
    cmds:
      - tools/bin/php-cs-fixer fix
    silent: true

  phpstan:
    cmds:
      - tools/bin/phpstan analyse
    silent: true

  phpunit:
    cmds:
      - tools/bin/phpunit
    silent: true

  infection:
    cmds:
      - tools/bin/infection --min-msi=90 --min-covered-msi=90 --threads=max
    silent: true

  ci:
    cmds:
      - task: cs
      - task: phpstan
      - task: phpunit
      - task: infection
    silent: true
