# https://taskfile.dev

version: '3'

vars:
  RUN_CMD:
    sh: 'if [ -f /.dockerenv ] || [ "$CI" = "true" ] || [ "$GITHUB_ACTIONS" = "true" ]; then echo ""; else echo "docker compose exec php "; fi'

tasks:
  cs:
    cmds:
      - '{{.RUN_CMD}}tools/bin/php-cs-fixer check'
    silent: true

  cs.fix:
    cmds:
      - '{{.RUN_CMD}}tools/bin/php-cs-fixer fix'
    silent: true

  phpstan:
    cmds:
      - '{{.RUN_CMD}}tools/bin/phpstan analyse --memory-limit=256M'
    silent: true

  units:
    cmds:
      - '{{.RUN_CMD}}tools/pest/vendor/bin/pest'
    silent: true

  coverage:
    cmds:
      - '{{.RUN_CMD}}tools/pest/vendor/bin/pest --coverage --min=70'
    silent: true

  infection:
    cmds:
      - '{{.RUN_CMD}}tools/bin/infection'
    silent: true

  behat:
    cmds:
      - '{{.RUN_CMD}}tools/bin/behat -f progress'
    silent: true

  cq:
    cmds:
      - task: cs
      - task: phpstan
    silent: true

  ci:
    cmds:
      - task: cs
      - task: phpstan
      - task: units
      - task: coverage
      - task: infection
      - task: behat
    silent: true