name: CI

on:
  pull_request: ~
  push: ~

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Task
        uses: go-task/setup-task@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: xdebug

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Coding Standard
        run: tools/bin/php-cs-fixer check

      - name: Static Analysis
        run: tools/bin/phpstan

      - name: Unit Tests
        run: tools/bin/paratest

      - name: Infection
        run: tools/bin/infection

      - name: Behat
        run: tools/bin/behat